import { describe, expect, it } from 'vitest';
import { xdr } from '@stellar/stellar-sdk';
import { decodeEscrow, decodeStatus } from '../src/codec';
import { EscrowStatus } from '../src/types';

/**
 * These base64 blobs are real XDR emitted by the compiled Rust contract
 * itself (not hand-constructed) — generated by
 * `cargo test print_sample_escrow_xdr_for_client_fixture -- --nocapture` in
 * Blockchain/contracts/escrow, which serializes an actual `Escrow` struct
 * and `EscrowStatus` value via the same `soroban_sdk` XDR encoding the
 * deployed contract will use. This is what makes these codec tests a real
 * cross-language check instead of an assumption about the wire format.
 */
const SAMPLE_ESCROW_XDR_B64 =
  'AAAAEQAAAAEAAAAGAAAADwAAAAZhbW91bnQAAAAAAAoAAAAAAAAAAAAAAAAdzWUAAAAADwAAAAdhcmJpdGVyAAAAABIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAPAAAABWJ1eWVyAAAAAAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAA8AAAAGc2VsbGVyAAAAAAASAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAADwAAAAZzdGF0dXMAAAAAABAAAAABAAAAAQAAAA8AAAAIRGlzcHV0ZWQAAAAPAAAABXRva2VuAAAAAAAAEgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABA==';

describe('decodeEscrow', () => {
  it('decodes a real contract-emitted Escrow struct', () => {
    const scVal = xdr.ScVal.fromXDR(SAMPLE_ESCROW_XDR_B64, 'base64');
    const escrow = decodeEscrow(scVal);

    expect(escrow.amount).toBe(500_000_000n);
    expect(escrow.status).toBe(EscrowStatus.Disputed);
    expect(escrow.buyer).toMatch(/^C[A-Z0-9]{55}$/);
    expect(escrow.seller).toMatch(/^C[A-Z0-9]{55}$/);
    expect(escrow.arbiter).toMatch(/^C[A-Z0-9]{55}$/);
    expect(escrow.token).toMatch(/^C[A-Z0-9]{55}$/);
    expect(escrow.buyer).not.toBe(escrow.seller);
  });

  it('decodes each real status variant, matching the [tag] shape the contract emits', () => {
    expect(decodeStatus(['Created'])).toBe(EscrowStatus.Created);
    expect(decodeStatus(['Funded'])).toBe(EscrowStatus.Funded);
    expect(decodeStatus(['Released'])).toBe(EscrowStatus.Released);
    expect(decodeStatus(['Refunded'])).toBe(EscrowStatus.Refunded);
    expect(decodeStatus(['Disputed'])).toBe(EscrowStatus.Disputed);
  });

  it('throws a clear error for an unrecognized status tag', () => {
    expect(() => decodeStatus(['NotARealStatus'])).toThrow(/Unrecognized escrow status/);
  });
});
